language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - nightly

matrix:
  allow_failures:
    - python: nightly

install:
    - pip install -U pip setuptools
    - pip install -U -e ".[dev]"

script:
  - make test
